import type { Klass, Lang, Session } from "@/lib/cycles";

export const COPY = {
  vi: {
    wordmark: "168",
    sub: "GRID",
    kicker: "Hai lưới · hai kỷ nguyên",
    lead: "Trend leaders (BTC ETH SOL BNB) tách khỏi rổ alt. Mean tính trên nến 1h Binance spot thật — không đoán. Pre-ETF không trộn vào Spot ETF: mẫu cũ làm loãng.",
    tzUtc: "UTC",
    tzVn: "VN UTC+7",
    now: "Bây giờ",
    live: "Live",
    metricKlass: "Chu kỳ",
    metricMean: "Mean",
    metricWin: "Win",
    samplePre: "Pre-ETF",
    sampleEtf: "Spot ETF",
    bookLeaders: "Trend leaders",
    bookAlts: "Altcoin",
    bookLeadersHint: "BTC · ETH · SOL · BNB · equal-weight mỗi giờ UTC",
    bookAltsHint: "XRP ADA DOGE AVAX LINK DOT ATOM LTC UNI NEAR · equal-weight",
    meanRecalc: "Mean đã kiểm chứng",
    meanRecalcHint:
      "Binance Vision spot 1h, nến đóng. Pre-ETF 1/1/2021–10/1/2024. Spot ETF 11/1/2024–26/8/2026. Prime leaders +0.044% trước ETF, −0.010% sau ETF. Alt Prime −0.024%.",
    sessMeans: "Mean theo phiên",
    dowMeans: "Mean theo thứ",
    feeNote: "Edge nhỏ hơn phí taker. Không phải tín hiệu vào lệnh.",
    coins: "Prime từng coin · cửa sổ đang chọn",
    spread: "Alt − Leader",
    all: "Tất cả",
    klass: {
      prime: "Prime",
      strong: "Strong",
      flow: "Flow",
      thin: "Thin",
      avoid: "Avoid",
    } satisfies Record<Klass, string>,
    klassHint: {
      prime: "T3–T4 × overlap 13–17 UTC. Trước ETF dương. Sau ETF âm — alt âm hơn leader.",
      strong: "T3–T4 phiên Âu, hoặc T2/T5 overlap.",
      flow: "Ngày thường, thanh khoản bình thường. Cửa sổ còn dương sau ETF.",
      thin: "Cuối tuần hoặc dead zone 22–02 UTC. Alt Sunday âm, leader không.",
      avoid: "Cuối tuần × dead zone. Mean không âm nhưng σ vẫn lớn.",
    } satisfies Record<Klass, string>,
    sess: {
      "asia-open": "Á mở",
      "asia-close": "Á đóng",
      europe: "Âu",
      overlap: "Overlap L–NY",
      ny: "New York",
      dead: "Dead zone",
    } satisfies Record<Session, string>,
    grid: "Lưới 168",
    gridHint: "Hai bảng riêng. Màu chung một thang. Bấm ô để soi. F = giờ in funding.",
    layers: "7 lớp ngay bây giờ",
    layerIntraday: "Intraday",
    layerWeekly: "Weekly",
    layerMonthly: "Monthly",
    layerSeason: "Mùa vụ",
    layerHalving: "Halving",
    layerMacro: "Vĩ mô",
    layerAlt: "Alt / BTC.D",
    week: { 1: "Tuần 1 · payday", 2: "Tuần 2 · tích lũy", 3: "Tuần 3 · pre-expiry", 4: "Tuần 4 · rebalance" },
    season: { q1: "Q1 · January effect", q2: "Q2 · Sell in May", q3: "Q3 · Rektember", q4: "Q4 · Uptober" },
    halving: {
      accumulation: "Accumulation",
      markup: "Markup",
      distribution: "Distribution",
      markdown: "Markdown",
    },
    macro: "Fed / M2 / DXY — lớp trên cùng của báo cáo. BTC−DXY −0.45, BTC−M2 +0.55.",
    alt: "Luân chuyển BTC → ETH → large cap → meme. Alt Sunday Spot ETF −0.012%, leaders +0.005%.",
    inspect: "Ô được chọn",
    mean: "Mean ô",
    win: "Win ô",
    n: "Mẫu",
    std: "σ",
    classAgg: "Lớp trên cửa sổ này",
    fund: "Funding rate",
    fundLead:
      "Perpetual BTC-USDT, 8h. Reset 00 / 08 / 16 UTC. 7.298 lần in 2020–2026. Báo cáo: >0.03% giảm long, <−0.02% thêm long.",
    fundNow: "Funding hiện tại",
    fundAnn: "Quy năm",
    fundNext: "Tới lần in",
    fundRule: "Lọc",
    fundHourNow: "Đúng giờ in — tránh mở lệnh lớn ±5 phút",
    fundHourOff: "Không phải giờ in",
    fundLiveNote: "OKX swap live. Lịch sử Binance UM.",
    fundPath: "Spot ± quanh giờ in",
    fundPathHint: "Khi funding >0.03%, t+1…t+3 âm. Khi <−0.02%, squeeze +1.25%/8h (n=53).",
    fundRules: "Ngưỡng báo cáo → 8h sau",
    ruleK: {
      hi05: "> 0.05% crowded long",
      hi03: "> 0.03% giảm long",
      mild_pos: "0 … 0.03%",
      mild_neg: "−0.02% … 0",
      lo02: "< −0.02% thêm long",
      lo03: "< −0.03% crowded short",
    },
    fundYear: "Crowding theo năm",
    fundY: "Năm",
    fundAvg: "Funding TB",
    fundHi: ">0.03%",
    fundR8: "Spot 8h",
    fundClass: "In trong từng lớp 168",
    fundSpark: "Funding TB theo tháng",
    fundHint:
      "Tương quan funding → 8h sau chỉ −0.026. 2021: 30% lần in >0.03%. 2025–26: 0%. Giờ này +0.007%/8h — dưới ngưỡng, ĐỢI. Edge nhỏ hơn phí.",
    regime: {
      "crowd-long": "Crowded LONG",
      reduce: "Giảm long",
      wait: "ĐỢI",
      add: "Thêm long",
      "crowd-short": "Crowded SHORT",
    },
    source: "Nguồn",
    disclaimer:
      "Nến Binance spot USDT 1h (data.binance.vision), nến đóng. Leaders = BTC ETH SOL BNB. Alts = 10 large-cap. Hai kỷ nguyên không trộn. Không phải lời khuyên đầu tư.",
  },
  en: {
    wordmark: "168",
    sub: "GRID",
    kicker: "Two books · two eras",
    lead: "Trend leaders (BTC ETH SOL BNB) sit on a different 168 table than the alt basket. Means are real Binance spot 1h closes — not guessed. Pre-ETF is not mixed into Spot ETF: the old sample dilutes the live number.",
    tzUtc: "UTC",
    tzVn: "VN UTC+7",
    now: "Now",
    live: "Live",
    metricKlass: "Cycle",
    metricMean: "Mean",
    metricWin: "Win",
    samplePre: "Pre-ETF",
    sampleEtf: "Spot ETF",
    bookLeaders: "Trend leaders",
    bookAlts: "Altcoins",
    bookLeadersHint: "BTC · ETH · SOL · BNB · equal-weight each UTC hour",
    bookAltsHint: "XRP ADA DOGE AVAX LINK DOT ATOM LTC UNI NEAR · equal-weight",
    meanRecalc: "Means, verified",
    meanRecalcHint:
      "Binance Vision spot 1h, closed bars. Pre-ETF 1 Jan 2021–10 Jan 2024. Spot ETF 11 Jan 2024–26 Aug 2026. Prime leaders +0.044% before the ETF, −0.010% after. Alt Prime −0.024%.",
    sessMeans: "Mean by session",
    dowMeans: "Mean by weekday",
    feeNote: "Edge is smaller than taker fees. Not a trade signal.",
    coins: "Prime by coin · selected window",
    spread: "Alt − Leader",
    all: "All",
    klass: {
      prime: "Prime",
      strong: "Strong",
      flow: "Flow",
      thin: "Thin",
      avoid: "Avoid",
    } satisfies Record<Klass, string>,
    klassHint: {
      prime: "Tue–Wed × overlap 13–17 UTC. Green before the ETF. Red after — alts redder than leaders.",
      strong: "Tue–Wed Europe, or Mon/Thu overlap.",
      flow: "Weekday, ordinary liquidity. Still the positive window after the ETF.",
      thin: "Weekend or the 22–02 UTC dead zone. Alt Sundays go red; leaders do not.",
      avoid: "Weekend × dead zone. Mean is not red, but σ stays wide.",
    } satisfies Record<Klass, string>,
    sess: {
      "asia-open": "Asia open",
      "asia-close": "Asia close",
      europe: "Europe",
      overlap: "L–NY overlap",
      ny: "New York",
      dead: "Dead zone",
    } satisfies Record<Session, string>,
    grid: "168 grid",
    gridHint: "Two separate tables. Shared color scale. Tap a cell. F = funding print hour.",
    layers: "7 layers right now",
    layerIntraday: "Intraday",
    layerWeekly: "Weekly",
    layerMonthly: "Monthly",
    layerSeason: "Season",
    layerHalving: "Halving",
    layerMacro: "Macro",
    layerAlt: "Alt / BTC.D",
    week: { 1: "Week 1 · payday", 2: "Week 2 · grind", 3: "Week 3 · pre-expiry", 4: "Week 4 · rebalance" },
    season: { q1: "Q1 · January effect", q2: "Q2 · Sell in May", q3: "Q3 · Rektember", q4: "Q4 · Uptober" },
    halving: {
      accumulation: "Accumulation",
      markup: "Markup",
      distribution: "Distribution",
      markdown: "Markdown",
    },
    macro: "Fed / M2 / DXY — the report’s top layer. BTC−DXY −0.45, BTC−M2 +0.55.",
    alt: "Rotation BTC → ETH → large cap → meme. Alt Sundays in Spot ETF −0.012%; leaders +0.005%.",
    inspect: "Selected cell",
    mean: "Cell mean",
    win: "Cell win",
    n: "n",
    std: "σ",
    classAgg: "Class on this sample",
    fund: "Funding rate",
    fundLead:
      "BTC-USDT perpetual, 8h. Prints 00 / 08 / 16 UTC. 7,298 prints 2020–2026. Report: >0.03% cut longs, <−0.02% add longs.",
    fundNow: "Live funding",
    fundAnn: "Annualised",
    fundNext: "Next print",
    fundRule: "Filter",
    fundHourNow: "Print hour — skip new size ±5 min",
    fundHourOff: "Not a print hour",
    fundLiveNote: "OKX swap live. History from Binance UM.",
    fundPath: "Spot around the print",
    fundPathHint: "When funding >0.03%, t+1…t+3 go red. When <−0.02%, squeeze +1.25%/8h (n=53).",
    fundRules: "Report thresholds → next 8h",
    ruleK: {
      hi05: "> 0.05% crowded long",
      hi03: "> 0.03% cut long",
      mild_pos: "0 … 0.03%",
      mild_neg: "−0.02% … 0",
      lo02: "< −0.02% add long",
      lo03: "< −0.03% crowded short",
    },
    fundYear: "Crowding by year",
    fundY: "Year",
    fundAvg: "Mean funding",
    fundHi: ">0.03%",
    fundR8: "Spot 8h",
    fundClass: "Prints inside each 168 class",
    fundSpark: "Monthly mean funding",
    fundHint:
      "Funding → next 8h correlation is only −0.026. 2021: 30% of prints >0.03%. 2025–26: 0%. Live +0.007%/8h — under the cut, WAIT. Edge is smaller than fees.",
    regime: {
      "crowd-long": "Crowded LONG",
      reduce: "Cut long",
      wait: "WAIT",
      add: "Add long",
      "crowd-short": "Crowded SHORT",
    },
    source: "Source",
    disclaimer:
      "Binance spot USDT 1h (data.binance.vision), closed bars. Leaders = BTC ETH SOL BNB. Alts = 10 large-caps. Eras are not mixed. Not advice.",
  },
} as const;

export function t(lang: Lang) {
  return COPY[lang];
}
